spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        followerEventChannel:
          name: follower_channel
        achievementEventChannel:
          name: achievement_channel
        comment:
          name: comment_channel
        goalSetChannel:
          name: goal_set_channel

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

achievements:
  achievements-title:
    evil-commenter: "EVIL COMMENTER"
  achievement-points-needed:
    evil-commenter: 100

goal-set: 
  points-needed: 100
  name: "Collector"